version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    environment:
      NO_IPS_EXCEPTHOOK: True
    steps:
      - checkout
      - run: pip install -r requirements.txt

      # this is OK for unit tests but not recommended for production!
      - run: cp deployment/config-example.ini config-production.ini
      - run: python manage.py test
